// Environment variable loader for GitHub Pages
// This will be replaced by build script with actual values
window.ENV = {
    FIREBASE_API_KEY: '{{FIREBASE_API_KEY}}',
    FIREBASE_AUTH_DOMAIN: '{{FIREBASE_AUTH_DOMAIN}}',
    FIREBASE_PROJECT_ID: '{{FIREBASE_PROJECT_ID}}',
    FIREBASE_STORAGE_BUCKET: '{{FIREBASE_STORAGE_BUCKET}}',
    FIREBASE_MESSAGING_SENDER_ID: '{{FIREBASE_MESSAGING_SENDER_ID}}',
    FIREBASE_APP_ID: '{{FIREBASE_APP_ID}}',
    FIREBASE_MEASUREMENT_ID: '{{FIREBASE_MEASUREMENT_ID}}',
    SUPABASE_URL: '{{SUPABASE_URL}}',
    SUPABASE_ANON_KEY: '{{SUPABASE_ANON_KEY}}'
};